export const ROUTES = {
	ANY_SECTION: '/*',
	LOGIN: '/login',
	MAIN: '/',
	REGISTRATION: '/register',
	NEW_WORK: '/new-work',
	WORKS: '/works',
	ACCOUNT: '/account',
	WORK_INFO: '/work',
	WORKS_GROUP: '/works-group',
	REPORT_WORK: '/report-work',
	RATE_WORK_PARTICIPANTS: '/rate-participants',
	WORK_REVIEW: '/work-review',
	REPORT_REVIEW: '/report-review',
	ADMIN_PANEL: '/admin-panel',
	ABOUT_US: '/about-us',
};
